apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
        - name: go-api
          image: aws-yuito-sandbox_go-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
